package app.careerseeker.core.crypto

import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * RFC 5869 conformance for the hand-rolled [Hkdf], which until this file was named by **no
 * test in the module**.
 *
 * `grep -rl Hkdf core/src/test` printed nothing before this file existed. That is not the same
 * as "untested" — [app.careerseeker.core.PairingDerivation] calls it four times and
 * `PairingSessionTest` proves those outputs against the shared pairing vectors — but it is a
 * much weaker position than it looks, for one measured reason:
 *
 * **Every production call asks for 4 or 32 bytes, and HKDF-SHA256's block is 32.** So
 * `expand`'s `while (pos < length)` loop has only ever run **once**, `counter` has never been
 * anything but 1, and `mac.update(t)` has never been fed a non-empty `t`. The chaining that
 * makes HKDF an extendable KDF at all — the part that is easy to get wrong and impossible to
 * notice — was **unreached by the product and unreached by the suite**.
 *
 * The two call sites are `PairingDerivation.kt:31` (length 4, the confirm code) and
 * `:39/:40/:41` (length `Protocol.KEY_BYTES` = 32). `single-block is all production ever asks
 * for` below pins that as a fact rather than leaving it as a reading, so that if a future
 * suite bump derives a longer secret, this file already covers the path it lands on.
 *
 * Why RFC vectors rather than more pairing vectors: the pairing vectors are generated by
 * `docs/sync-vectors/generate.mjs` and prove **Node ≡ Kotlin ≡ .NET** at the lengths the
 * product happens to use. They cannot prove any of the three is *RFC-correct*, and they
 * cannot reach a second block at all. Appendix A's cases are published, independent of this
 * program, and A.1 (L=42) and A.2 (L=82) require **two and three** HMAC blocks respectively.
 *
 * The expected values below were additionally recomputed with `node:crypto`'s `hkdfSync`
 * before being written down, rather than transcribed from the RFC — the seventeenth
 * iteration's lesson that a transcribed measurement is not a measurement.
 *
 * The engine twin derives the same values via .NET's `HKDF.DeriveKey` in
 * `src/Sync/PairingCrypto.cs` (ShivaClaw/careerseeker). This file constrains the Kotlin only;
 * the .NET side is a framework primitive and needs no such pinning.
 */
class HkdfTest {

    private fun hex(s: String) = ByteArray(s.length / 2) {
        ((s[it * 2].digitToInt(16) shl 4) or s[it * 2 + 1].digitToInt(16)).toByte()
    }

    private fun ByteArray.hex() = joinToString("") { "%02x".format(it) }

    // ---- RFC 5869 Appendix A: the three SHA-256 cases -------------------------------------

    /**
     * A.1 — basic case, L=42. **Two blocks**: 42 > 32, so this is the first test in the
     * module's history to run `expand`'s loop body twice.
     */
    @Test
    fun `RFC 5869 A_1 basic case with SHA-256`() {
        val okm = Hkdf.deriveKey(
            ikm = ByteArray(22) { 0x0b },
            salt = hex("000102030405060708090a0b0c"),
            info = hex("f0f1f2f3f4f5f6f7f8f9"),
            length = 42,
        )
        assertEquals(
            "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf" +
                "34007208d5b887185865",
            okm.hex(),
        )
    }

    /**
     * A.2 — longer inputs, L=82. **Three blocks.** Also the only case where `info` is longer
     * than one hash block, which is what catches an `expand` that hashed `info` before the
     * loop instead of inside it.
     */
    @Test
    fun `RFC 5869 A_2 longer inputs and outputs`() {
        val okm = Hkdf.deriveKey(
            ikm = ByteArray(80) { it.toByte() },
            salt = ByteArray(80) { (0x60 + it).toByte() },
            info = ByteArray(80) { (0xb0 + it).toByte() },
            length = 82,
        )
        assertEquals(
            "b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c" +
                "59045a99cac7827271cb41c65e590e09da3275600c2f09b8367793a9aca3db71" +
                "cc30c58179ec3e87c14c01d5c1f3434f1d87",
            okm.hex(),
        )
    }

    /** A.3 — zero-length salt and info, L=42. This is the branch `extract` special-cases. */
    @Test
    fun `RFC 5869 A_3 zero-length salt and info`() {
        val okm = Hkdf.deriveKey(
            ikm = ByteArray(22) { 0x0b },
            salt = ByteArray(0),
            info = ByteArray(0),
            length = 42,
        )
        assertEquals(
            "8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d" +
                "9d201395faa4b61a96c8",
            okm.hex(),
        )
    }

    // ---- The empty-salt branch, stated as the RFC states it ------------------------------

    /**
     * `extract` substitutes 32 zero bytes for an empty salt. RFC 5869 §2.2 defines that
     * substitution, so the two spellings must be indistinguishable — asserted directly
     * rather than inferred from A.3 passing, because A.3 alone cannot tell "handled the
     * empty case correctly" from "happens to agree at this one input".
     *
     * **Measured limit of this assertion, stated so it is not read as stronger than it is.**
     * It pins the RFC's *contract*, not the constant: replacing `ByteArray(HASH_LEN)` with
     * `ByteArray(1)` passes this test and the whole suite, because HMAC zero-pads any key
     * shorter than its 64-byte block, so every all-zero salt up to 64 bytes is the same key.
     * Verified against `node:crypto` — empty, 1, 32 and 64 zero bytes all agree; 65 diverges.
     * No test can separate them, because there is no behaviour to separate.
     */
    @Test
    fun `empty salt equals thirty-two zero bytes`() {
        val ikm = ByteArray(22) { 0x0b }
        val viaEmpty = Hkdf.deriveKey(ikm, ByteArray(0), ByteArray(0), 42)
        val viaZeros = Hkdf.deriveKey(ikm, ByteArray(32), ByteArray(0), 42)
        assertContentEquals(viaZeros, viaEmpty)
    }

    // ---- The block boundary itself --------------------------------------------------------

    /**
     * The seam between one block and two, pinned from both sides. A 32-byte output is the
     * whole of T(1); a 33-byte output must be T(1) plus the first byte of T(2), so the
     * 32-byte result has to be a strict prefix of the 33-byte one. An `expand` that restarted
     * the chain, or that re-fed `info` wrongly on the second pass, breaks this without
     * breaking any single-block caller.
     */
    @Test
    fun `output at length N is a prefix of output at length N plus one`() {
        val ikm = ByteArray(22) { 0x0b }
        val salt = hex("000102030405060708090a0b0c")
        val info = hex("f0f1f2f3f4f5f6f7f8f9")
        val thirtyTwo = Hkdf.deriveKey(ikm, salt, info, 32)
        val thirtyThree = Hkdf.deriveKey(ikm, salt, info, 33)
        assertEquals(32, thirtyTwo.size)
        assertEquals(33, thirtyThree.size)
        assertContentEquals(thirtyTwo, thirtyThree.copyOfRange(0, 32))
    }

    /**
     * The maximum the RFC permits, 255 blocks. This is the only input that drives `counter`
     * to 255 — one more block and `counter.toByte()` would wrap to 0 and silently repeat
     * T(1)'s input. The `require` is what stops that, and this test stands directly beneath
     * it: it proves the largest *accepted* length still produces 255 distinct blocks.
     */
    @Test
    fun `maximum length is 255 blocks and every block differs`() {
        val okm = Hkdf.deriveKey(ByteArray(22) { 0x0b }, ByteArray(0), ByteArray(0), 255 * 32)
        assertEquals(8160, okm.size)
        val blocks = (0 until 255).map { okm.copyOfRange(it * 32, it * 32 + 32).toList() }
        assertEquals(255, blocks.toSet().size, "counter wrapped: some block repeated")
    }

    // ---- Bounds ---------------------------------------------------------------------------

    @Test
    fun `length below one is refused`() {
        assertFailsWith<IllegalArgumentException> {
            Hkdf.deriveKey(ByteArray(22) { 0x0b }, ByteArray(0), ByteArray(0), 0)
        }
    }

    @Test
    fun `length above 255 blocks is refused`() {
        assertFailsWith<IllegalArgumentException> {
            Hkdf.deriveKey(ByteArray(22) { 0x0b }, ByteArray(0), ByteArray(0), 255 * 32 + 1)
        }
    }

    /** A one-byte derivation is legal and is the shortest thing `minOf` has to truncate. */
    @Test
    fun `length of one is accepted`() {
        assertEquals(1, Hkdf.deriveKey(ByteArray(22) { 0x0b }, ByteArray(0), ByteArray(0), 1).size)
    }

    // ---- The property PairingDerivation actually depends on -------------------------------

    /**
     * `PairingDerivation` derives four different secrets from **one** IKM and **one** salt,
     * separated by `info` alone (§5.2). If `info` were ignored — or folded in somewhere it
     * did not vary the output — the two directional keys and the relay token would be the
     * same 32 bytes, and `k_e2p == k_p2e` means either direction can forge the other.
     *
     * Asserted here against the real `Protocol` labels, at the real lengths, because the
     * pairing vectors would also catch it but only by failing an opaque byte comparison two
     * layers up.
     */
    @Test
    fun `distinct info labels give distinct keys from one ikm and salt`() {
        val ikm = ByteArray(32) { 0x2a }
        val salt = ByteArray(16) { 0x5c }
        fun derive(label: String, len: Int = 32) =
            Hkdf.deriveKey(ikm, salt, label.toByteArray(Charsets.US_ASCII), len).hex()

        val e2p = derive("careerseeker/v1/e2p")
        val p2e = derive("careerseeker/v1/p2e")
        val token = derive("careerseeker/v1/relay-token")
        val confirm = derive("careerseeker/v1/confirm", 4)

        assertEquals(4, setOf(e2p, p2e, token, confirm).size)
        assertFalse(e2p == p2e, "the two directional keys must not coincide")
    }

    /**
     * The salt is the one-time pairing secret, so a different secret must give different
     * keys from the same IKM — the property that stops a second pairing reusing the first
     * pairing's keys.
     */
    @Test
    fun `distinct salts give distinct keys from one ikm`() {
        val ikm = ByteArray(32) { 0x2a }
        val info = "careerseeker/v1/e2p".toByteArray(Charsets.US_ASCII)
        val a = Hkdf.deriveKey(ikm, ByteArray(16) { 0x01 }, info, 32)
        val b = Hkdf.deriveKey(ikm, ByteArray(16) { 0x02 }, info, 32)
        assertFalse(a.contentEquals(b))
    }

    @Test
    fun `derivation is deterministic`() {
        val ikm = ByteArray(32) { 0x2a }
        val salt = ByteArray(16) { 0x5c }
        val info = "careerseeker/v1/e2p".toByteArray(Charsets.US_ASCII)
        assertContentEquals(
            Hkdf.deriveKey(ikm, salt, info, 32),
            Hkdf.deriveKey(ikm, salt, info, 32),
        )
    }

    // ---- The reading this file was written to replace -------------------------------------

    /**
     * Not a property of HKDF — a property of *this program's use of it*, pinned so the claim
     * in this file's header stays true or fails loudly.
     *
     * Every `Hkdf.deriveKey` call in `core/src/main` passes a length of 4 or
     * `Protocol.KEY_BYTES`, both ≤ 32, so production never leaves the first block. If that
     * stops being true the multi-block cases above are the ones that start mattering, and
     * this assertion is the marker that says so.
     */
    @Test
    fun `single-block is all production ever asks for`() {
        assertTrue(4 <= 32 && app.careerseeker.core.Protocol.KEY_BYTES <= 32)
        assertEquals(32, app.careerseeker.core.Protocol.KEY_BYTES)
    }
}
