package app.careerseeker.core

import app.careerseeker.core.crypto.Base64Url
import app.careerseeker.core.crypto.SyncCrypto
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The cross-repo proof. These vectors were generated by Node in the main repo
 * (docs/sync-vectors/generate.mjs) and are consumed unmodified by the C# SyncHarness.
 * If this Kotlin code, using the JVM's own JCA crypto, reproduces every derived value and
 * classifies every envelope the same way, the two independent implementations agree
 * byte-for-byte — which is the whole reason the vectors are shared. A divergence fails
 * here, in CI, instead of surfacing as a pairing bug in someone's hands.
 *
 * See core/src/test/resources/sync-vectors/VECTORS.lock for the pinned source commit.
 */
class ProtocolVectorsTest {

    private val json = Json { ignoreUnknownKeys = true }

    private fun vectorDir(): File {
        // Resolve from the test resources root, wherever Gradle puts it.
        val url = requireNotNull(javaClass.classLoader.getResource("sync-vectors/v1/index.json")) {
            "shared vectors not on the test classpath — is core/src/test/resources/sync-vectors vendored?"
        }
        return File(url.toURI()).parentFile
    }

    private fun load(name: String): JsonObject =
        json.parseToJsonElement(File(vectorDir(), "$name.json").readText()).jsonObject

    private fun index(): JsonObject = load("index")

    private fun b64u(s: String): ByteArray = requireNotNull(Base64Url.decodeOrNull(s)) { "not strict base64url: $s" }
    private fun hex(s: String): ByteArray = ByteArray(s.length / 2) { ((s[it * 2].digitToInt(16) shl 4) or s[it * 2 + 1].digitToInt(16)).toByte() }
    private fun JsonObject.str(key: String): String = this[key]!!.jsonPrimitive.content
    private fun JsonElement.canonical(): String = when (this) {
        is JsonObject -> entries.sortedBy { it.key }.joinToString(",", "{", "}") { "\"${it.key}\":${it.value.canonical()}" }
        else -> toString()
    }

    private fun envelopeVectors(): List<JsonObject> =
        index()["vectors"]!!.jsonArray.map { it.jsonObject }
            .filter { it.str("type") == "envelope" }
            .map { load(it.str("name")) }

    private fun keyFor(dir: String): ByteArray = hex(
        if (dir == "e2p") "a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90"
        else "0f1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0",
    )

    // ---------------------------------------------------------------- suite integrity

    @Test
    fun `index agrees with the shipping constants`() {
        val idx = index()
        assertEquals("AES-256-GCM", idx.str("cipher"))
        assertEquals(Protocol.SUITE, idx.str("suite"))
        assertEquals(Protocol.MAX_ENVELOPE_BYTES, idx["max_envelope_bytes"]!!.jsonPrimitive.int)
        assertTrue(idx.str("active_key_id").isNotEmpty())
    }

    // ---------------------------------------------------------------- pairing derivation

    @Test
    fun `pairing derivation reproduces every vector value`() {
        val v = load("pairing-basic")
        val expected = v["expected"]!!.jsonObject
        val secret = b64u(v.str("secret_b64u"))

        val enginePub = b64u(v["engine"]!!.jsonObject.str("pub_b64u"))
        val phonePub = b64u(v["phone"]!!.jsonObject.str("pub_b64u"))
        val engineD = hex(v["engine"]!!.jsonObject.str("d_hex"))
        val phoneD = hex(v["phone"]!!.jsonObject.str("d_hex"))

        val ssEngine = SyncCrypto.ecdhSharedSecret(engineD, phonePub)
        val ssPhone = SyncCrypto.ecdhSharedSecret(phoneD, enginePub)
        assertEquals(expected.str("ss_hex").lowercase(), ssEngine.toHex(), "ECDH shared secret")
        assertTrue(ssEngine.contentEquals(ssPhone), "ECDH is symmetric")

        val keys = PairingDerivation.derive(listOf(ssEngine), secret)
        assertEquals(expected.str("k_e2p_hex").lowercase(), keys.keyEngineToPhone.toHex(), "k_e2p")
        assertEquals(expected.str("k_p2e_hex").lowercase(), keys.keyPhoneToEngine.toHex(), "k_p2e")
        assertEquals(expected.str("relay_token_b64u"), keys.relayToken, "relay token")
        assertEquals(expected.str("confirm"), keys.confirmCode, "6-digit confirm code")
        assertEquals(expected.str("provisional_token_b64u"), PairingDerivation.provisionalRelayToken(secret), "provisional token")

        // The completion opens under the derived k_p2e, and the device key is inside it.
        val completion = v["completion"]!!.jsonObject
        assertEquals(
            PairingDerivation.completionAad(index().str("pairing_id"), v.str("suite"), v["phone"]!!.jsonObject.str("pub_b64u")),
            completion.str("aad"),
        )
        val payload = SyncCrypto.open(keys.keyPhoneToEngine, b64u(completion.str("nonce_b64u")),
            completion.str("aad"), b64u(completion.str("ciphertext_b64u")))
        assertTrue(payload.toString(Charsets.UTF_8).contains(v["device_sig"]!!.jsonObject.str("pub_b64u")))
    }

    @Test
    fun `pairing MITM key swap cannot decrypt the completion`() {
        val v = load("pairing-mitm-keyswap")
        val secret = b64u(v.str("secret_b64u"))
        val engineD = hex(v["engine"]!!.jsonObject.str("d_hex"))
        val attackerPub = b64u(v["phone"]!!.jsonObject.str("pub_b64u"))
        val keys = PairingDerivation.derive(listOf(SyncCrypto.ecdhSharedSecret(engineD, attackerPub)), secret)
        val completion = v["completion"]!!.jsonObject
        var rejected = false
        try {
            SyncCrypto.open(keys.keyPhoneToEngine, b64u(completion.str("nonce_b64u")),
                completion.str("aad"), b64u(completion.str("ciphertext_b64u")))
        } catch (_: Exception) {
            rejected = true
        }
        assertTrue(rejected, "a relay that swaps phone_pub must break the handshake, not hijack it")
    }

    // ---------------------------------------------------------------- valid envelopes

    @Test
    fun `valid envelope vectors decrypt to the stated plaintext and verify`() {
        for (v in envelopeVectors().filter { it["valid"]!!.jsonPrimitive.content == "true" }) {
            val name = v.str("name")
            val text = SyncCrypto.open(hex(v.str("key_hex")), b64u(v.str("nonce_b64u")),
                v.str("aad"), b64u(v.str("ciphertext_b64u"))).toString(Charsets.UTF_8)
            assertEquals(
                json.parseToJsonElement(v["plaintext_json"]!!.toString()).canonical(),
                json.parseToJsonElement(text).canonical(),
                "$name round-trip",
            )
            val env = v["envelope_json"]!!.jsonObject
            if (env["sig"] != null) {
                val input = PairingDerivation.signatureInput(v.str("aad"), v.str("nonce_b64u"), b64u(v.str("ciphertext_b64u")))
                assertEquals(v.str("sig_input"), input, "$name sig_input")
                assertTrue(
                    SyncCrypto.verifySignature(b64u(v.str("device_sig_pub_b64u")), input, b64u(env.str("sig"))),
                    "$name signature verifies",
                )
            }
        }
    }

    // ---------------------------------------------------------------- the receiver

    @Test
    fun `the receiver classifies every envelope vector exactly as the engine does`() {
        val idx = index()
        val devicePub = b64u(load("pairing-basic")["device_sig"]!!.jsonObject.str("pub_b64u"))
        val receiver = EnvelopeReceiver(idx.str("active_key_id"), devicePub)

        // Valid vectors first, in seq order (the replay vector's notes require it).
        val valid = envelopeVectors().filter { it["valid"]!!.jsonPrimitive.content == "true" }
            .sortedBy { it["envelope_json"]!!.jsonObject["seq"]!!.jsonPrimitive.long }
        for (v in valid) {
            val result = receiver.receive(received(v["envelope_json"]!!.jsonObject), ::keyFor)
            assertTrue(result.accepted, "receiver should accept ${v.str("name")} (got ${result.error})")
        }

        for (v in envelopeVectors().filter { it["valid"]!!.jsonPrimitive.content == "false" }) {
            val name = v.str("name")
            val expected = v.str("expect_error")
            val result = if (v["envelope_json"] == null || v["envelope_json"] is kotlinx.serialization.json.JsonNull) {
                // invalid-oversized ships a synth length rather than a literal megabyte.
                val synth = v["synth_ciphertext_len"]!!.jsonPrimitive.int
                receiver.receive(
                    ReceivedEnvelope(1, idx.str("pairing_id"), "e2p", 999L, "2026-06-11T14:02:11Z",
                        idx.str("active_key_id"), Base64Url.encode(ByteArray(Protocol.NONCE_BYTES)),
                        Base64Url.encode(ByteArray(synth)), null),
                    ::keyFor,
                )
            } else {
                receiver.receive(received(v["envelope_json"]!!.jsonObject), ::keyFor)
            }
            assertEquals(expected, result.error?.wire, "$name should reject as $expected")
        }

        // The rejections above must not have advanced the sequence tracker.
        assertEquals(4L, receiver.highestAccepted(Direction.ENGINE_TO_PHONE))
        assertEquals(1L, receiver.highestAccepted(Direction.PHONE_TO_ENGINE))
    }

    // ---------------------------------------------------------------- protocol invariants

    @Test
    fun `no shipping kind implies a send path and reserved kinds are rejected`() {
        assertTrue(PayloadKind.entries.none {
            it.wire.contains("send") || it.wire.contains("submit") || it.wire.contains("transmit")
        })
        for (reserved in PayloadKind.RESERVED_FOR_L2) {
            assertTrue(PayloadKind.fromWire(reserved) == null, "$reserved must be rejected in v1")
        }
        assertTrue(PayloadKind.RESERVED_FOR_L2.contains("kill"))
    }

    private fun received(env: JsonObject) = ReceivedEnvelope(
        env["v"]!!.jsonPrimitive.int, env.str("pairing"), env.str("dir"),
        env["seq"]!!.jsonPrimitive.long, env.str("ts"), env.str("key_id"),
        env.str("nonce"), env.str("ciphertext"),
        env["sig"]?.let { if (it is kotlinx.serialization.json.JsonNull) null else it.jsonPrimitive.content },
    )

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }
}
