#!/usr/bin/env bash
#
# core-probe.sh — run :core's test suite on a machine with no Android SDK.
#
# WHY THIS EXISTS
#
# B-7 records that this program's cloud sandboxes cannot resolve Google-hosted
# artifacts (dl.google.com is denied by the egress policy). For seven iterations
# that was read as "no Kotlin can be verified here", and claims about :core code
# were written as "read, not executed".
#
# That was broader than the fact. Measured 2026-08-11 (eighteenth iteration):
#
#   services.gradle.org   200
#   repo1.maven.org       200
#   plugins.gradle.org    200
#   dl.google.com/dl/android/maven2/   000   <- the only denial
#
# :core is a pure-Kotlin/JVM module by construction (settings.gradle.kts, and
# the root project's checkCoreIsAndroidFree task). Every one of its dependencies
# -- the Kotlin JVM plugin, kotlinx-serialization-json, ktor-client-core,
# kotlin-test, ktor-client-mock, kotlinx-coroutines-test -- lives on Maven
# Central. It needs nothing from Google.
#
# What blocks the repo's own build here is not :core. It is the ROOT build
# script, which declares `alias(libs.plugins.android.application) apply false`,
# and the :app module -- both of which resolve AGP from google(). So this script
# does not build the repository. It builds a throwaway Gradle build that includes
# :core and only :core, pointed at the repository's own core/ directory and its
# own version catalog, with google() deliberately absent from the repositories
# block.
#
# WHAT THIS IS NOT
#
# This is NOT the android gate. The gate is
#   ./gradlew checkCoreIsAndroidFree :core:test :app:assembleDebug :app:lintDebug
# and four of those five still need the Android SDK. This script runs exactly one
# of them. Do not report a gate result on the strength of it; report ":core:test,
# via scripts/core-probe.sh" and say what did not run.
#
# One property it does establish that the real build does not: because google()
# is absent from the resolver entirely, a successful run proves :core resolves
# with the Android repository unreachable. checkCoreIsAndroidFree asserts the
# same rule by scanning imports and the plugins block; this asserts it at the
# dependency-resolution layer, which is a different and independent check.
#
# USAGE
#   scripts/core-probe.sh            # run :core:test
#   scripts/core-probe.sh --rerun    # ignore Gradle's up-to-date checks
#
# The repository working tree is never modified. Gradle writes build output to
# core/build/, which .gitignore already covers.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# :core pins jvmToolchain(17). Gradle's auto-provisioning downloads from
# api.foojay.io, which the sandbox egress policy also denies (measured: 000), so
# the JDK has to be present already. Fail with the fix rather than with Gradle's
# "Toolchain download repositories have not been configured", which sends the
# reader to the wrong page.
if ! ls -d /usr/lib/jvm/*17* >/dev/null 2>&1; then
    cat >&2 <<'MSG'
core-probe: no JDK 17 found under /usr/lib/jvm.

:core pins jvmToolchain(17), and Gradle cannot auto-provision one here --
api.foojay.io is denied by the same egress policy as dl.google.com (B-7).

On a Debian/Ubuntu sandbox:

    apt-get update -qq && apt-get install -y --no-install-recommends openjdk-17-jdk-headless

(apt-get install alone may 404 against a stale index; the update is not optional.)
MSG
    exit 1
fi

probe_dir="$(mktemp -d)"
trap 'rm -rf "$probe_dir"' EXIT

# Written fresh on every run, deliberately. A checked-in second settings file is
# a thing that drifts from the real one silently; generating it from the repo's
# own catalog and module means there is nothing to keep in sync.
cat > "$probe_dir/settings.gradle.kts" <<EOF
// Generated by scripts/core-probe.sh. Not part of the build.
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
    repositories {
        // google() is deliberately absent -- see the header of core-probe.sh.
        mavenCentral()
    }
    versionCatalogs {
        create("libs") {
            from(files("$repo_root/gradle/libs.versions.toml"))
        }
    }
}

rootProject.name = "coreprobe"
include(":core")
project(":core").projectDir = file("$repo_root/core")
EOF

: > "$probe_dir/build.gradle.kts"

args=(:core:test --no-daemon --console=plain)
if [[ "${1:-}" == "--rerun" ]]; then
    args+=(--rerun-tasks)
fi

echo "core-probe: running :core:test against $repo_root/core (no Android SDK, no google() repo)"
"$repo_root/gradlew" -p "$probe_dir" "${args[@]}"

# Gradle prints per-test lines, but the number that gets copied into records
# should come from the XML, not from counting console output by eye.
python3 - "$repo_root" <<'PY'
import glob, sys, xml.etree.ElementTree as ET

tests = failures = skipped = 0
classes = 0
for path in glob.glob(f"{sys.argv[1]}/core/build/test-results/test/*.xml"):
    root = ET.parse(path).getroot()
    classes += 1
    tests += int(root.get("tests"))
    failures += int(root.get("failures")) + int(root.get("errors"))
    skipped += int(root.get("skipped"))

print(f"core-probe: {tests} tests, {failures} failed, {skipped} skipped, across {classes} classes")
if failures:
    sys.exit(1)
PY
