#!/usr/bin/env bash
#
# firing-line.sh — one no-change firing, in one line.
#
# WHY THIS EXISTS
#
# B-18 records that this routine keeps firing past its own stop condition. Six
# attempts have been logged against it. Attempts 3-6 all lowered the READ cost of
# a firing: run 48 put a banner where the reader looks, run 53 pushed the facts
# outside the repository, and run-zero.sh reaches ground state in one command.
#
# None of them touched the WRITE cost, and run 118 measured it for the first
# time. A no-change firing adds a median of ~355 lines to the four house records
# (runs 111-117: 327, 321, 380, 392, 336, 361, 355), which stood at 50,862 lines
# when this script was written. On 2026-08-28 the schedule fired five times, so
# that is roughly 1,700 lines a day of restatement.
#
# That cost is not merely wasteful, it is self-defeating: every 355 lines added
# makes the next session's read longer, which is the exact cost run-zero.sh was
# built to remove. The two mitigations were working against each other.
#
# THE RULE THIS SCRIPT SERVES (house law from run 118; see FIRINGS.md)
#
# A firing whose run-zero.sh verdict is NOTHING MOVED and whose five escalation
# triggers are all negative appends ONE line to FIRINGS.md and writes to NONE of
# STATE.md, LOG.md, BLOCKED.md or AUDIT-REQUEST.md. A firing that finds anything
# — a moved main, a merged or undrafted PR, a changed prompt, an executed gate,
# or a genuine new finding — writes a full entry in the four records as before,
# and this script is not for it.
#
# WHAT THIS IS NOT
#
# This is NOT a gate and it runs no build, no suite and no Verify-Alpha.ps1. It
# derives every field from run-zero.sh's actual output, so a line cannot claim a
# state the probe did not report. The two board counts need the GitHub API, which
# a shell script here cannot reach (run-zero.sh section 6, same limit); they are
# REQUIRED ARGUMENTS, supplied by the session that queried them, and the script
# refuses to invent them.
#
# USAGE
#   scripts/firing-line.sh [--insert] <run-number> <engine-clone> <engine-open> <android-open> <esc-ledger> [note]
#
# EXAMPLE
#   scripts/firing-line.sh 118 ../careerseeker 22 6 11 'declined: S5 spec half, 83rd'
#   scripts/firing-line.sh --insert 243 ../careerseeker 3 6 19 'declined: S5 spec half, 191st'
#
# Without --insert it PRINTS the line and does not append it. Read it, then insert
# it yourself — INSIDE the fenced ledger block at the end of FIRINGS.md, under the
# last run. Do NOT use a bare `>> FIRINGS.md`: that appends after the closing ```
# fence and drops the line out of the block. Run 122 did exactly that and had to
# undo it.
#
# --insert DOES THE PLACEMENT FOR YOU, and exists because that warning failed.
# Added run 243. The paragraph above has been in this file since run 118 and is
# exact, and runs 240 and 241 each appended after the fence anyway; their two
# lines sat outside the block for three firings until run 243 found them by eye
# (C-243-1). Three misplacements in three attempts at a hand step is a defect in
# the step, not in the three sessions. --insert writes the line immediately above
# the LAST ``` in FIRINGS.md — the closing fence of the ledger block — and then
# re-runs run-zero.sh §3c to prove the file it just wrote is well-formed. If §3c
# is unhappy it restores the file and exits non-zero, so a bad insert cannot be
# committed by a session that did not look.

set -uo pipefail

insert=0
if [ "${1:-}" = "--insert" ]; then insert=1; shift; fi

if [ "$#" -lt 5 ]; then
  sed -n '/^# USAGE/,/^$/p' "$0" | sed 's/^# \{0,1\}//'
  exit 2
fi

run="$1"; engine="$2"; eng_open="$3"; and_open="$4"; ledger="$5"; note="${6:-}"
here="$(cd "$(dirname "$0")/.." && pwd)"

for n in "$run" "$eng_open" "$and_open" "$ledger"; do
  case "$n" in (*[!0-9]*|"") echo "firing-line: '$n' is not a number" >&2; exit 2;; esac
done

probe="$(bash "$here/scripts/run-zero.sh" "$engine" 2>&1)" || true

verdict=NOT-CLEAN
grep -q '^  NOTHING MOVED on every check' <<<"$probe" && verdict='NOTHING MOVED'

pin=$(grep -m1 '^  current pin' <<<"$probe" | awk '{print substr($4,1,7)}')
corpus=$(grep -m1 '^  vendored:' <<<"$probe" | awk '{print $2"/"$6}')
# run-zero prints two shapes per main, and until run 198 only the first had ever
# been seen, so only the first was ever parsed:
#     "  engine  main unmoved  aac05f3  (date)"        -> the sha is field 4
#     "  !! engine  main MOVED  aac05f3 -> 5395b57 ..." -> leading '!!', sha is after '->'
# The first MOVED verdict in 162 firings made this printf emit an EMPTY engine
# field, and run 198's line had to be hand-written -- which the house rule forbids
# ("generated by firing-line.sh, never hand-written"). Both shapes now parse, and
# the MOVED shape reports the NEW sha: the point of the field is where main is now.
main_sha() {  # $1 = 'engine' | 'android'
  local line
  line=$(grep -m1 -E "^ +(!! )?$1 +main " <<<"$probe") || return 0
  if grep -q 'MOVED' <<<"$line"; then
    sed -E 's/.*-> *([0-9a-f]+).*/\1/' <<<"$line"
  else
    sed -E 's/^ +(!! )?[a-z]+ +main +[a-z]+ +([0-9a-f]+).*/\2/' <<<"$line"
  fi
}
eng_main=$(main_sha engine)
and_main=$(main_sha android)
cites=$(grep -m1 '^  definitions:' <<<"$probe" | awk '{print $2"/"$4"/"$6}')
# Count-agnostic on purpose (run 203). This was pinned to the literal string
# 'OK: 29 vector files match the generator.'; run 202's re-pin took the corpus to
# 30 and the field silently became 'gen ?' -- a generated record reporting "I
# could not tell" while the generator was in fact green. Same class as the two
# constants run 198's addendum fixed. The COUNT is already reported by the
# corpus field, so this one only ever needed to answer OK / not-OK.
gen=$(grep -qE '^  OK: [0-9]+ vector files match the generator\.' <<<"$probe" && echo 'gen OK' || echo 'gen ?')

if [ -z "$pin$eng_main$and_main" ]; then
  echo "firing-line: run-zero.sh produced nothing parseable; write a full entry by hand" >&2
  exit 1
fi

line=$(printf '%s | %s | %s | pin %s | corpus %s | %s | mains %s/%s | cites %s | board %s+%s open | esc %s%s' \
  "$run" "$(date -u +%Y-%m-%d)" "$verdict" "$pin" "$corpus" "$gen" \
  "$eng_main" "$and_main" "$cites" "$eng_open" "$and_open" "$ledger" \
  "${note:+ | $note}")

printf '%s\n' "$line"

[ "$insert" -eq 1 ] || exit 0

# --- --insert: place it inside the fence, then prove the placement -----------
ledger_md="$here/FIRINGS.md"
[ -f "$ledger_md" ] || { echo "firing-line: $ledger_md is missing" >&2; exit 1; }

fence=$(grep -n '^```' "$ledger_md" | tail -1 | cut -d: -f1)
if [ -z "$fence" ]; then
  echo "firing-line: no closing fence found in FIRINGS.md — insert by hand" >&2
  exit 1
fi

backup=$(mktemp); cp "$ledger_md" "$backup"
awk -v n="$fence" -v l="$line" 'NR==n{print l} {print}' "$ledger_md" > "$ledger_md.tmp" \
  && mv "$ledger_md.tmp" "$ledger_md"

# §3c is the arbiter, not this script's own idea of where the line went.
#
# CAPTURED IN TWO STEPS, DELIBERATELY. The first draft of this check was
#   if bash run-zero.sh "$engine" 2>&1 | sed -n '/3c\./,/^== 4\./p' | grep -q '!!'
# and it reported GREEN on a line this very guard had just rejected. This file sets
# `set -uo pipefail`, so a pipeline's status is the last NON-ZERO exit in it: run-zero.sh
# exits 1 whenever any guard fails, which is precisely when grep matches, so the pipeline
# returned 1, the `if` read that as "no match", and the bad insert stood. The check could
# only ever have fired when there was nothing to find. Same class as C-242-1 — an
# instrument that cannot detect the thing it is pointed at — and caught here only because
# the negative case was actually exercised. Never put this grep back inside an `if`.
verdict3c="$(bash "$here/scripts/run-zero.sh" "$engine" 2>&1 | sed -n '/3c\./,/^== 4\./p')"
if printf '%s\n' "$verdict3c" | grep -q '!!'; then
  cp "$backup" "$ledger_md"; rm -f "$backup"
  printf '%s\n' "$verdict3c" | sed 's/^/  /' >&2
  echo "firing-line: §3c rejected the result; FIRINGS.md restored unchanged" >&2
  exit 1
fi
rm -f "$backup"
echo "firing-line: inserted at line $fence, inside the fence; §3c green." >&2
